#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(std430,  binding = 0) buffer writeonly buff_render { uint col[]; };
layout(rgba32f, binding = 1) uniform writeonly image2D img_canvas;

uint pos2id(ivec2 p){
    return uint(p.x + p.y*1920);
}

void main() {

    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(img_canvas);

    if(coord.x >= size.x || coord.y >= size.y) return;

    col[pos2id(coord)] = 0u;
    imageStore(img_canvas, coord, vec4(0.0));

}