// Triangulate the mesh and write the vertex positions into the output image
#version 460
layout(local_size_x = 256) in;

struct Halfedge { 
    uint to; 
    uint from; 
    uint next; 
    uint prev; 
    uint opposite; 
    uint face; 
    vec2 tex; };
    
struct Edge   { uvec2 halfedges; };
struct Vertex { vec3  point; };
struct Face   { uint  halfedge;  };

layout(std430, binding = 0) buffer readonly buff_halfedges { Halfedge halfedges[]; };
layout(std430, binding = 1) buffer readonly buff_faces     { Face faces[]; };
layout(std430, binding = 2) buffer readonly buff_vertices  { Vertex vertices[]; };
layout(std430, binding = 3) buffer readonly buff_faces_size { uint fs; };
layout(binding = 4, rgba32f) uniform writeonly image2D img_out;
layout(binding = 5, rgba32f) uniform writeonly image2D img_nor;

ivec2 id2pos(int id, ivec2 size){
    return ivec2(id % size.x, id / size.x);
}

void main(){
    uint gid = gl_GlobalInvocationID.x;
    if(gid >= fs) return;

    uint he0 = faces[gid].halfedge;
    uint he1 = halfedges[he0].next;
    uint v0 = halfedges[he0].from;
    uint v1 = halfedges[he1].from;
    uint v2 = halfedges[he1].to;
    vec3 p0 = vertices[v0].point;
    vec3 p1 = vertices[v1].point;
    vec3 p2 = vertices[v2].point;

    vec3 e10 = normalize(p1 - p0);
    vec3 e20 = normalize(p2 - p0);
    vec3 N = normalize(cross(e10, e20));

    ivec2 img_size = imageSize(img_out);
    int fistVert = int(gid*3u);

    ivec2 iuv;

    iuv = id2pos(fistVert + 0, img_size);
    imageStore(img_out, iuv, vec4(p0, 0.0));
    imageStore(img_nor, iuv, vec4(N, 0.0));

    iuv = id2pos(fistVert + 1, img_size);
    imageStore(img_out, iuv, vec4(p1, 0.0));
    imageStore(img_nor, iuv, vec4(N, 0.0));

    iuv = id2pos(fistVert + 2, img_size);
    imageStore(img_out, iuv, vec4(p2, 0.0));
    imageStore(img_nor, iuv, vec4(N, 0.0));
}