#version 460
layout(local_size_x = 128) in;

struct Key { uint hash; uint vertex; uint start; };

layout(std430, binding = 0) buffer readonly buff_keys { Key keys[]; };
layout(std430, binding = 1) buffer writeonly buff_sorted  { uint id[]; };
layout(std430, binding = 2) buffer readonly buff_vertices_size  { uint vs; };

void main() {

    uint gid = gl_GlobalInvocationID.x;

    if(gid >= vs) return;

    uint vertex = keys[gid].vertex;
    id[vertex] = gid;
}