#version 460
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, rg32f) readonly uniform image2D levelImg;
layout(binding = 1, rg32f) writeonly uniform image2D prevLevelImg;

void main() {

    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(levelImg);

    if(gid.x >= size.x || gid.y >= size.y) return;

    vec2 val = imageLoad(levelImg, gid).xy;

    imageStore(prevLevelImg, gid, vec4(val, 0.0, 0.0));
}
