#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(r32f, binding = 0) uniform image3D field;

void main()
{
    const ivec3 coord = ivec3(gl_GlobalInvocationID.xyz);
    const ivec3 size = imageSize(field);

    if (coord.x >= size.x || coord.y >= size.y || coord.z >= size.z) return;

    float curr = imageLoad(field, coord).x;
    imageStore(field, coord, vec4(max(curr - 0.05, 0.0)));
}
