// comp_build_leaf_keys.comp
#version 460
layout(local_size_x = 256) in;

struct Key {
    uint morton;
    uint primID;
};

layout(std430, binding = 0) readonly buffer buff_primKeys { Key primKey[]; };
layout(std430, binding = 1) writeonly buffer buff_leafKeys { Key leafKey[]; };

layout(binding = 2) uniform cfg {
    uint Nprims;
    uint Nleaves;
    uint leafSize; // 2..8
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= Nleaves) return;

    uint start = i * leafSize;           // start index in sorted primitive keys
    uint m = primKey[start].morton;      // representative morton for this leaf group

    leafKey[i].morton = m;
    leafKey[i].primID = i;              // not used by topology, but handy for debugging
}