#version 460

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer InputBuffer { float inData[]; };
layout(std430, binding = 1) writeonly buffer OutputBuffer { float outData[]; };
layout(std430, binding = 2) writeonly buffer BlockSumsBuffer { float blockSums[]; };

layout(binding = 3) uniform cfg {
    uint tri_count;
    uint writeBlockSums;
};

shared float sData[256];

void main()
{
    uint lid   = gl_LocalInvocationID.x;
    uint gid   = gl_GlobalInvocationID.x;
    uint group = gl_WorkGroupID.x;

    sData[lid] = (gid < tri_count) ? inData[gid] : 0.0;
    barrier();

    // Inclusive scan
    for (uint offset = 1u; offset < 256u; offset <<= 1u)
    {
        float sum = sData[lid];
        if (lid >= offset)
            sum += sData[lid - offset];

        barrier();
        sData[lid] = sum;
        barrier();
    }

    if (gid < tri_count)
        outData[gid] = sData[lid];

    if (writeBlockSums != 0u && lid == 255u)
        blockSums[group] = sData[255];
}