// Compute triangles' area
#version 460

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer readonly buff_vert { vec4 vert[]; };
layout(std430, binding = 1) buffer writeonly buff_area { float area[]; };
layout(binding = 2) uniform cfg{ uint tri_count; };

void main() {

    uint tri = gl_GlobalInvocationID.x;

    if(tri >= tri_count) return;

    uint v0 = tri*3u;
    uint v1 = v0+1u;
    uint v2 = v0+2u;

    vec3 p0 = vert[v0].xyz;
    vec3 p1 = vert[v1].xyz;
    vec3 p2 = vert[v2].xyz;

    area[tri] = 0.5 * length(cross(p1 - p0, p2 - p0));
}