#version 460
#define GOLDEN_RATIO 1.6180339887498948482

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer buff_vert { vec4 vert[]; };
layout(std430, binding = 1) readonly buffer buff_cdf { float cdf[]; };
layout(std430, binding = 2) writeonly buffer buff_points { vec4 outPoint[]; };
layout(std430, binding = 3) writeonly buffer buff_point_count { uint count[]; };
layout(std430, binding = 4) readonly buffer buff_halton { vec2 halton[]; };
layout(std430, binding = 5) readonly buffer buff_area { float area[]; };
layout(binding = 6) uniform cfg {
    uint point_count;
    uint tri_count;
};

// simple integer hash PRNG
uint hash_u32(uint x)
{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

float rand01(inout uint state)
{
    state = hash_u32(state);
    return float(state) * (1.0 / 4294967296.0); // [0,1)
}

// upper_bound on inclusive CDF:
// first index i such that cdf[i] > r
uint select_triangle(float r, uint tri_count)
{
    uint lo = 0u;
    uint hi = tri_count;

    while (lo < hi) {
        uint mid = (lo + hi) >> 1u;

        if (cdf[mid] <= r)
            lo = mid + 1u;
        else
            hi = mid;
    }

    return min(lo, tri_count - 1u);
}

void main()
{
    uint pid = gl_GlobalInvocationID.x;
    if (pid >= point_count || tri_count == 0u) return;

    float totalArea = cdf[tri_count - 1u];

    // unique RNG state per output point
    uint rng = pid * 747796405u + 2891336453u;

    // 1) pick triangle proportionally to area
    //float r = halton[pid % 1024u].x;
    //r = fract(r + floor(float(pid) / 1024)*GOLDEN_RATIO);
    //r *= totalArea;
    float r = rand01(rng) * totalArea;
    uint tri = select_triangle(r, tri_count);

    // 2) fetch its 3 vertices
    uint v0 = tri * 3u;
    uint v1 = v0 + 1u;
    uint v2 = v0 + 2u;

    vec3 p0 = vert[v0].xyz;
    vec3 p1 = vert[v1].xyz;
    vec3 p2 = vert[v2].xyz;

    // 3) uniform point inside triangle
    uint prev_count = atomicAdd(count[tri], 1u);
    uint selector = prev_count % 16384u;
    ivec2 iuv = ivec2(selector % 128u, selector/128u);
    vec2 stbn = halton[prev_count % 1024u];
    float offset = floor(float(prev_count / 1024u)) + 1.0;
    stbn = fract(stbn + GOLDEN_RATIO*vec2(tri*3, tri*2)*offset); //Cranley-Patterson rotation


    //float dimmer = 0.0001 / area[tri];
    //stbn.x += rand01(rng) * dimmer;
    //stbn.y += rand01(rng) * dimmer;
    //stbn = fract(stbn);

    bool inside = stbn.x + stbn.y <= 1.0;

    if (!inside) {
        stbn.x = 1 - stbn.x;
        stbn.y = 1 - stbn.y;
    }


    vec3 e10 = p1-p0;
    vec3 e20 = p2-p0;
    //float le10 = length(e10);
    //float le20 = length(e20);
    //float ratio0 = le20 / le10;
    //float ratio1 = 1.0 / ratio0;

    //ratio0 = max(1.0, ratio0);
    //ratio1 = max(1.0, ratio1);

    //stbn = fract(stbn * vec2(ratio0, ratio1));
    vec3 p = p0 + stbn.x*e10 + stbn.y*e20;

    outPoint[pid] = vec4(p, 1.0);
}