#version 460

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer coherent buff_tmpMin { vec4 tmpMin[]; };
layout(std430, binding = 1) buffer coherent buff_tmpMax { vec4 tmpMax[]; };
layout(        binding = 2) uniform cfg{ uint count; };

void main() {

    uint gid = gl_GlobalInvocationID.x;
    if(gid >= count) return;

    tmpMin[gid] = vec4( 1e30);
    tmpMax[gid] = vec4(-1e30);
}